In [ ]:
import time
from turtle import Turtle

john = Turtle()
print(john)
john.shape("turtle")
john.color("red", "green")
while True:
    john.forward(5)
    john.left(5)
    time.sleep(1)

In [8]:
f4 = open("./test2.txt", "r")
print(f4.read())

f4.seek(0)
print(f4.tell())

context = f4.readlines()
print(context)

f4.close()


hello
안녕
반가워
난, 코딩온이야
0
['hello\n', '안녕\n', '반가워\n', '난, 코딩온이야']


In [20]:
# with open("example.txt", "a") as file:
#     file.write("\n hi") #벗어나면 자동으로 닫는다

# with open("example.txt", "r") as file:
#     print(file.read())

# #이미 존재 하느 파일이라면 건드리는 게 무서워 새로운 파일로 만듬
#     with open("example.txt", "x") as file:
#         file.write("this is a new file") #벗어나면 자동으로 닫는다
    
with open("example.txt", "r")as file:
    for line in file:
        if line == "hi\n": #개행문자 숨어있음 "\n"
            print(line)

In [31]:
info = []

for _ in range(3):
    text = input("아이디 비밀번호 ex)유즈 123")
    info.append(text)

    with open("./text.txt","a")as f:
        for line in info:
            f.write(line + "\n")

In [25]:
#미리 한줄 읽기
with open("./text.txt", "r") as f:
    line = f.readline()
    while line:
        print(line.strip()) #개행문자 제거하여 출력 / strip()은 아무것도 적지 않으면 개행문자를 기준으로 삼음
        line = f.readline()

유즈 123
존 555
오쉣 55123


In [27]:
with open("text.txt", "r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.rstrip("\n"))

유즈 123
존 555
오쉣 55123


In [9]:
info = []

for _ in range(3):
    text = input("아이디 비밀번호 ex)유즈 123")
    info.append(text)

with open("./member.txt","a")as f:
        for line in info:
            f.write(line + "\n")

with open("./member.txt", "r") as f:
    lines = f.read()

    print(lines.rstrip())

이즈 123
치즈 123
시즈 123



In [4]:
id = []
password = []
info = []
h_p = []

# for _ in range(3):
#     id_p = input("아이디 비밀번호 ex)유즈 123")
#     info.append(id_p)

# with open("./member.txt","a")as mem:
#         for line in info:
#             mem.write(line + "\n")

with open("./member.txt","r")as mem:
       
    mylist = mem.readlines()
    id = input("아이디를 입력하세요 : ")
    password = input("비밀번호를 입력하세요 : ")
    for line in mylist:
     
        name, pw = line.split()
        if id == name and password == pw.rstrip("\n"):
            print("로그인 성공.")
            tel = input(" 전화 번호를 입력하세요.")
            with open("./member_tel.txt","a")as mem_tel:
                mem_tel.write(id), mem_tel.write(tel)
                break
        else:
            print("로그인 실패")
            break
            


로그인 성공.


In [ ]:
name = input("input name")
pw = input("input pw")
isLogin = False
with open("member.txt","r") as file:
  lines = file.readlines()
  file.seek(0)
  for line in lines:
    text = line.split()# [ name, pw ]
    if len(text) >= 2 and text[0] == name and text[1] == pw:
      isLogin= True
      break
if isLogin:
  print("log in")
else :
  print("log in failed")
if isLogin:
  telNum = input("input tel num")
  with open("member_tel.txt","r+") as file:
    lines = file.readlines()
    file.seek(0)
    for i, line in enumerate(lines): # mylist = ['A', 'B', 'C'] -> (0, 'A'), (1, 'B'), (2,'C')
      text = line.split()
      if text and text[0] == name:
        lines[i] = f"{name} {telNum}\n"
        break
    else:
      lines.append(f"{name} {telNum}\n")
    file.writelines(lines)

In [ ]:
# try:
#     num=[1,2,3,4]
#     print(who)
# except:
#     print("알 수 없는 예외가 발생했씁니다")


try:
    num = int(input("숫자 입력"))
except ValueError:
    num = int(input("숫자 입력"))
    print(f"""숫자 입력:{num}
          정수가 아님 정수를 입력해주세요""")
except NameError:
    num = int(input("숫자 입력"))
    print(f"""숫자 입력:{num}
          정수가 아님 정수를 입력해주세요""")
else:
    print("정수 입력 성공")
    


In [ ]:
while True:
    try:
        num=int(input("숫자 입력"))
        print("정수 입력 성공 :", num)
        break
    except ValueError:
        print("정수가 아님 정수를 입력해주세요")

In [22]:
import numpy as np
x=np.array([3,1,2])
print(x)
type(x)

[3 1 2]


numpy.ndarray

In [28]:
import numpy as np
print(np.full((1,10),0))
# ndarr = np.array([[0,0], [0,0], [1,0],[0,0],[0,0]])
# ndarr.flatten()

# np.random.randint(10, 30, size=(1,10))
# np.random.randint(0,100 , size=(2,2))
# np.random.rand(2,4)


[[0 0 0 0 0 0 0 0 0 0]]


In [34]:

date = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
an1 = np.unique(date)
print(an1)

an2 = np.max(an1)
an2_1 = np.min(an1)
an2_2 = np.mean(an1)
an3 = np.sum(an1)
an4 = np.median(date)

print(f"""
{an1}
{an2}
{an2_1}
{an2_2}
{an3}
{an4}""")

[  1   2   3   4   5   7   8   9  10  11  24 100]

[  1   2   3   4   5   7   8   9  10  11  24 100]
100
1
15.333333333333334
184
5.0


In [18]:
import pandas as pd
growth = pd.Series([143, 150, 157, 160], index=['2018','2019','2020','2021'])
growth

150

In [31]:
index=['2018','2019','2020','2021']

y_h=pd.Series([143,150,157,160], index=index)
c_s=pd.Series([165,172,175,180], index=index)

growth=pd.DataFrame({'영희' : y_h, '철수' : c_s})

growth.head()

영희   철수
2018  143  165
2019  150  172
2020  157  175
2021  160  180